import './globals.css'
import type { Metadata } from 'next'
import { Klee_One } from 'next/font/google'

<<<<<<< HEAD
const klee = Klee_One({
=======
const zen = Zen_Kurenaido ({
>>>>>>> parent of 02260d9 (update layout.tsx, page.tsx and exam_temprate.tsx)
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={klee.className}>
      <body>{children}</body>
    </html>
  )
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

