FROM archlinux

LABEL version="0.2.0"
LABEL maintainer="haru"
LABEL name="timetable-frontend-next"

RUN pacman -Syu --noconfirm 
RUN pacman -S --noconfirm nodejs
RUN pacman -S --noconfirm npm
RUN pacman -S --noconfirm yarn
RUN pacman -S --noconfirm git
RUN pacman -S --noconfirm github-cli

ENV PATH /root/.local/bin:$PATH